### PR TITLE
Simplify GraphImpl internals further

### LINKED ISSUE #119: Simplify GraphImpl internals further
- VertexPlacement is only used in VTableReplicated, so it should be created on demand there rather than being passed around in GraphImpl.
- VTableReplicated should be renamed to ReplicatedVertexView.
- VertexPlacement should be renamed to VertexRoutingTable.

### PR DESCRIPTION
**Pull request by ankurdave**
**Depends on #120. Incremental diff: https://github.com/ankurdave/graphx/compare/6d1bf0d...more-simplify**
- VertexPlacement is only used in VTableReplicated, so this PR creates it on demand there rather than passing it around in GraphImpl.
- Rename VTableReplicated to ReplicatedVertexView.

Closes #119.

### CODE REVIEW

**Comment by jegonzal** [comment]
I like the name changes but I am a little concerned we are not fully reusing the routing tables?  Is the routing table associated with the view or with the edges?  Conceptually the edge table defines the routing so routing information should evolve with the EdgeRDD.  For example in operations like 'mapVertices' or 'outerJoinVertices' the routing table remains the same even when the vertex type changes.  In the current design it appears that the routing tables are lost in these cases.

**Comment by ankurdave** [comment]
Oops, you're right. Since the routing table is associated with the edges, maybe it would make sense to generate and memoize it in EdgeRDD instead.

**Comment by ankurdave** [comment]
I just fixed this issue. I reverted to passing the routing table around in GraphImpl instead of putting it in EdgeRDD, because some operations (e.g., `reverse` and `mapEdges`) keep the routing table but change the edge RDD.

**Comment by ankurdave** [comment]
Jenkins, retest this please.

**Comment by jegonzal** [comment]
Looks good to me!

**Pull request merged**
